# Generated by Django 4.1.7 on 2023-05-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('Sname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Sage', models.IntegerField()),
                ('Sadress', models.CharField(max_length=100)),
                ('Smno', models.IntegerField()),
            ],
        ),
    ]
